# Misc
set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
set(CMAKE_LIBRARY_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_SOURCE_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG ${CMAKE_SOURCE_DIR}/bin)
set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE ${CMAKE_SOURCE_DIR}/bin)
# Policies
set(CMAKE_POLICY_DEFAULT_CMP0069 NEW CACHE STRING "Set policy on IPO/LTO" FORCE)
# check for IPO/LTO
include(CheckIPOSupported)
check_ipo_supported(RESULT LTO_ENABLED LANGUAGES C CXX)
set(OPTION_BUILD_WITH_LTO               ${LTO_ENABLED} CACHE BOOL "Build glbinding with Link-time Optimization" FORCE)
set(CMAKE_INTERPROCEDURAL_OPTIMIZATION  ${LTO_ENABLED} CACHE BOOL "Build with Link-time Optimization by default" FORCE)