set(SDL_SHARED       ON  CACHE BOOL "Build SDL as shared lib" FORCE)
set(SDL_STATIC       OFF CACHE BOOL "Build SDL as static lib" FORCE)
set(SDL_TEST_LIBRARY OFF CACHE BOOL "Build SDL tests" FORCE)
set(SDL_ATOMIC       OFF CACHE BOOL "Disable SDL Atomic subsystem" FORCE)
set(SDL_AUDIO        ON  CACHE BOOL "Disable SDL Audio subsystem" FORCE)
set(SDL_VIDEO        ON  CACHE BOOL "Disable SDL Video subsystem" FORCE)
set(SDL_RENDER       OFF CACHE BOOL "Disable SDL Render subsystem" FORCE)
set(SDL_EVENTS       ON  CACHE BOOL "Disable SDL Events subsystem" FORCE)
set(SDL_JOSTICK      OFF CACHE BOOL "Disable SDL Joystick subsystem" FORCE)
set(SDL_HAPTIC       OFF CACHE BOOL "Disable SDL Haptic subsystem" FORCE)
set(SDL_HIDAPI       ON  CACHE BOOL "Disable SDL Hidapi subsystem" FORCE)
set(SDL_POWER        OFF CACHE BOOL "Disable SDL Power subsystem" FORCE)
set(SDL_THREADS      ON  CACHE BOOL "Disable SDL Threads subsystem" FORCE)
set(SDL_TIMERS       OFF CACHE BOOL "Disable SDL Timers subsystem" FORCE)
set(SDL_FILE         ON  CACHE BOOL "Disable SDL File subsystem" FORCE)
set(SDL_LOADSO       ON  CACHE BOOL "Disable SDL Loadso subsystem" FORCE)
set(SDL_CPUINFO      OFF CACHE BOOL "Disable SDL CPUinfo subsystem" FORCE)
set(SDL_FILESYSTEM   ON  CACHE BOOL "Disable SDL Filesystem subsystem" FORCE)
set(SDL_SENSOR       OFF CACHE BOOL "Disable SDL Sensor subsystem" FORCE)
set(SDL_LOCALE       ON  CACHE BOOL "Disable SDL Locale subsystem" FORCE)
set(SDL_MISC         ON  CACHE BOOL "Disable SDL Misc subsystem" FORCE)

set(SDL3MIXER_VENDORED ON)